# **1. Python Fundamentals**

## 1.1 Variables & Data Types  

### Checking Types

In [ ]:
type(10)
type(10.0)

float

In [ ]:
print(isinstance(10, int))       
isinstance("abc", (int, str))

True


True

### String Manipulation

In [8]:
name = "John"
greeting = f"Hello, {name}!"   # f-string
length = len(name)

print(greeting, length)

Hello, John! 4


In [9]:
"hello".upper()   # "HELLO"
"Hello".lower()   # "hello"
"data".capitalize()   # "Data"

'Data'

## 1.2 Basic Operations 

### Assignement Operations

In [10]:
x=1 
x*=2 

print(x)  

2


## 2.3 Dictionnaries

In [1]:
person = {
    "name": "Pierre",
    "age": 25,
    "is_student": False
}

empty_dict = {}

In [2]:
person["name"]        # 'Pierre'
person.get("age")     # 25

person.get("salary", 0) #No error if missing

0

In [ ]:
person.keys()
person.values()
person.items()

dict_items([('name', 'Pierre'), ('age', 25), ('is_student', False)])

In [4]:
a = {1, 2, 3}
b = {3, 4, 5}

a | b

{1, 2, 3, 4, 5}

# 4.2 Functions ``*args`` and ``*kwargs``

In [ ]:
def add_all(*args):
    return sum(args)
add_all(1, 2, 3, 4)

10

In [2]:
def print_info(**kwargs):
    for key, value in kwargs.items():
        print(key, value)

print_info(name="Alice", age=30)

name Alice
age 30


# 9 - Useful Python Features

In [ ]:
def log_call(func):
    def wrapper(*args, **kwargs):
        print("Function called")
        return func(*args, **kwargs)
    return wrapper


@log_call
def add(a, b):
    return a + b

print(add(3, 4))  

Function called
7


# 10 - NumPy Essentials

In [ ]:
import numpy as np

In [9]:
print(np.zeros(3))
print(np.ones((2, 3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [11]:
a = np.array([1, 2, 3])

In [16]:
a.shape
a.ndim
a.size
a.dtype 

dtype('int64')

In [17]:
a = np.array([1, 2, 3])

a + 10
a * 2
a ** 2

array([1, 4, 9])

In [18]:
x = np.array([1, 2, 3])
y = 10

x + y

array([11, 12, 13])

# Manipulation example

### Create a palindrome function

In [1]:
def isPalindrome(word) : 
    word = word.lower().replace(" ", "")

    return word == word [::-1]

Palendrome = "radar"

isPalindrome(Palendrome)

True

### Create a function to check if the product of values in a table are 60

In [2]:
def value_check(t): 
    for i in t:
        for j in t:
            for k in t:
                if i * j * k == 60:
                    return True
                
    return False

table = [2, 3, 4, 5]

value_check(table)

True

### Maximum value without max function

In [ ]:
def max(T): 
    maximum = T[0]
    for value in T:
        if value > maximum:
            maximum = value
    return maximum